"""Routes that serve the minimal HTML frontend and SAMPLE downloads.

These are intentionally lightweight — no templating engine, no SPA. Just
plain static files with correct MIME / Content-Disposition so officers can
open the Imports page in any browser and download sample workbooks that
launch directly in Excel with Hindi text and formatting intact.
"""
from __future__ import annotations
import logging
from pathlib import Path

from flask import Blueprint, abort, send_file, send_from_directory

from .. import config
from ..utils import envelope_error

log = logging.getLogger(__name__)
bp = Blueprint("static_pages", __name__)

# Frontend root (sibling of backend/)
FRONTEND_DIR = config.ROOT_DIR / "frontend"

# kind  ->  master_data/SAMPLE_*.xlsx  (the canonical filenames generated by
# scripts/generate_sample_excels.py)
SAMPLE_FILENAMES: dict[str, str] = {
    "consumers":  "SAMPLE_raid_master_data.xlsx",
    "historical": "SAMPLE_all_data.xlsx",
    "current":    "SAMPLE_raid_excell_2526.xlsx",
    "devices":    "SAMPLE_device_list.xlsx",
    "rates":      "SAMPLE_slab_rates.xlsx",
    "mapping":    "SAMPLE_account_mapping.xlsx",
}

XLSX_MIME = (
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
)


@bp.get("/imports")
def imports_page():
    """Serve the static Imports page (single self-contained HTML)."""
    page = FRONTEND_DIR / "imports.html"
    if not page.exists():
        return envelope_error(
            "imports.html missing on server. Re-deploy frontend/.",
            status=500, code="FRONTEND_MISSING",
        )
    return send_file(
        page,
        mimetype="text/html",
        max_age=0,  # always fresh — devs iterate quickly
    )


@bp.get("/frontend/<path:filename>")
def frontend_static(filename: str):
    """Serve any other static asset under frontend/ (CSS / JS / images)."""
    return send_from_directory(FRONTEND_DIR, filename, max_age=0)


@bp.get("/samples/<kind>")
def download_sample(kind: str):
    """Stream a SAMPLE_*.xlsx with proper Excel MIME and download disposition.

    The browser triggers a file save (Content-Disposition: attachment) with
    the canonical SAMPLE filename so a double-click opens it directly in
    Excel. Hindi (UTF-8) text and openpyxl formatting are preserved because
    we ship the raw .xlsx bytes — no transformation.
    """
    fname = SAMPLE_FILENAMES.get(kind)
    if not fname:
        valid = ", ".join(SAMPLE_FILENAMES)
        return envelope_error(
            f"Unknown sample kind '{kind}'. Valid: {valid}",
            status=404, code="BAD_KIND",
        )
    path: Path = config.MASTER_DATA_DIR / fname
    if not path.exists():
        log.warning("Sample missing: %s — run scripts/generate_sample_excels.py", path)
        return envelope_error(
            f"Sample file not found on server: {fname}. "
            "Run `python scripts/generate_sample_excels.py` to generate it.",
            status=404, code="SAMPLE_MISSING",
        )
    return send_file(
        path,
        mimetype=XLSX_MIME,
        as_attachment=True,
        download_name=fname,
        max_age=0,
    )
